debug:
  enabled: false

maps:
  available:
    - game

games:
  max-parallel: 10

teams:
  max-players-per-team: 4
  count: 4

players:
  max: 16
  min-percent-to-start: 0.125

world:
  border-size: 261.0
  template-name: game