settings:
  protection-radius: 2.0
  void-kill-height: 50
  infinite-food: true

allowed-blocks:
  - OAK_PLANKS
  - CLAY
  - END_STONE
  - OBSIDIAN
  - WHITE_TERRACOTTA
  - RED_TERRACOTTA
  - BLUE_TERRACOTTA
  - GREEN_TERRACOTTA
  - YELLOW_TERRACOTTA
  - ORANGE_TERRACOTTA
  - MAGENTA_TERRACOTTA
  - LIGHT_BLUE_TERRACOTTA
  - LIME_TERRACOTTA
  - PINK_TERRACOTTA
  - GRAY_TERRACOTTA
  - LIGHT_GRAY_TERRACOTTA
  - CYAN_TERRACOTTA
  - PURPLE_TERRACOTTA
  - BROWN_TERRACOTTA
  - BLACK_TERRACOTTA
  - WHITE_WOOL
  - RED_WOOL
  - BLUE_WOOL
  - GREEN_WOOL
  - YELLOW_WOOL
  - ORANGE_WOOL
  - MAGENTA_WOOL
  - LIGHT_BLUE_WOOL
  - LIME_WOOL
  - PINK_WOOL
  - GRAY_WOOL
  - LIGHT_GRAY_WOOL
  - CYAN_WOOL
  - PURPLE_WOOL
  - BROWN_WOOL
  - BLACK_WOOL
  - TNT

day-night-cycle:
  day-duration-ticks: 6000
  night-duration-ticks: 6000
  eyeblossom-open-percent: 0.5
  creaking-aggro-radius: 60.0
  creakingBreakSpeed: 10.0

respawn:
  delay-seconds: 10
  spectator-mode: true

resources:
  rubber_low:
    material: RESIN_CLUMP
    display-name: "§7Резина"
    spawn-period: 60 # ticks
    tier: 1

  rubber_mid:
    material: RESIN_BRICK
    display-name: "§6Прочная резина"
    spawn-period: 180
    tier: 2

  rubber_high:
    material: NETHERITE_INGOT
    display-name: "§dСлишком прочная резина"
    spawn-period: 360
    tier: 3

  eyeblossom:
    material: OPEN_EYEBLOSSOM
    display-name: "§2Открытая глазалия"
    spawn-period: -1  # NOT spawn automatically
    tier: 3


trades:
  wool:
    cost: "rubber_low:4"
    result: "WHITE_WOOL:16"
    display-name: "Шерсть"
    category: "blocks"

  terracotta:
    cost: "rubber_low:12"
    result: "WHITE_TERRACOTTA:16"
    display-name: "Обожжённая глина"
    category: "blocks"

  end_stone:
    cost: "rubber_mid:6"
    result: "END_STONE:12"
    display-name: "Эндерстоун"
    category: "blocks"

  planks:
    cost: "rubber_mid:4"
    result: "OAK_PLANKS:16"
    display-name: "Доски"
    category: "blocks"

  obsidian:
    cost: "eyeblossom:2"
    result: "OBSIDIAN:1"
    display-name: "Обсидиан"
    category: "blocks"

  stone_sword:
    cost: "rubber_low:10"
    result: "STONE_SWORD:1"
    display-name: "Каменный меч"
    category: "swords"

  iron_sword:
    cost: "rubber_mid:7"
    result: "IRON_SWORD:1"
    display-name: "Железный меч"
    category: "swords"

  netherite_sword:
    cost: "eyeblossom:4"
    result: "NETHERITE_SWORD:1"
    display-name: "Незеритовый меч"
    category: "swords"

  knockback_stick:
    cost: "rubber_mid:15"
    result: "STICK:1"
    display-name: "Откидывающая палка"
    category: "swords"
    enchantments:
      - "KNOCKBACK:2"

  chainmail_armor:
    cost: "rubber_low:40"
    result: "CHAINMAIL_LEGGINGS:1"
    display-name: "Кольчужная броня"
    category: "armor"

  iron_armor:
    cost: "rubber_mid:12"
    result: "IRON_LEGGINGS:1"
    display-name: "Железная броня"
    category: "armor"

  netherite_armor:
    cost: "eyeblossom:6"
    result: "NETHERITE_LEGGINGS:1"
    display-name: "Незеритовая броня"
    category: "armor"

  # Tools
  wooden_pickaxe:
    cost: "rubber_low:20"
    result: "WOODEN_PICKAXE:1"
    display-name: "Деревянная кирка"
    category: "tools"

  wooden_axe:
    cost: "rubber_low:20"
    result: "WOODEN_AXE:1"
    display-name: "Деревянный топор"
    category: "tools"

  stone_pickaxe:
    cost: "rubber_low:25"
    result: "STONE_PICKAXE:1"
    display-name: "Каменная кирка"
    category: "tools"

  stone_axe:
    cost: "rubber_low:25"
    result: "STONE_AXE:1"
    display-name: "Каменный топор"
    category: "tools"

  iron_pickaxe:
    cost: "rubber_low:30"
    result: "IRON_PICKAXE:1"
    display-name: "Железная кирка"
    category: "tools"

  iron_axe:
    cost: "rubber_low:30"
    result: "IRON_AXE:1"
    display-name: "Железный топор"
    category: "tools"

  netherite_pickaxe:
    cost: "rubber_mid:9"
    result: "NETHERITE_PICKAXE:1"
    display-name: "Незеритовая кирка"
    category: "tools"

  netherite_axe:
    cost: "rubber_mid:12"
    result: "NETHERITE_AXE:1"
    display-name: "Незеритовый топор"
    category: "tools"

  shears:
    cost: "rubber_low:16"
    result: "SHEARS:1"
    display-name: "Ножницы"
    category: "tools"

  fireball:
    cost: "rubber_low:40"
    result: "FIRE_CHARGE:1"
    display-name: "Огненный шар"
    category: "special"

  tnt:
    cost: "rubber_low:40"
    result: "TNT:1"
    display-name: "Динамит"
    category: "special"

  golden_apple:
    cost: "rubber_mid:3"
    result: "GOLDEN_APPLE:1"
    display-name: "Золотое яблоко"
    category: "special"

  ender_eye:
    cost: "eyeblossom:2"
    result: "ENDER_PEARL:1"
    display-name: "Эндер-дисса"
    category: "special"

upgrades:
  forge:
    tier-1:
      cost: "rubber_high:10"
      multiplier: 1.25
    tier-2:
      cost: "rubber_high:15"
      multiplier: 1.5
    tier-3:
      cost: "rubber_high:25"
      multiplier: 2.0
    tier-4:
      cost: "rubber_high:35"
      multiplier: 3.0

  protection:
    tier-1:
      cost: "rubber_high:10"
      level: 1
    tier-2:
      cost: "rubber_high:20"
      level: 2
    tier-3:
      cost: "rubber_high:30"
      level: 3

  sharpness:
    cost: "rubber_high:10"
    level: 1

  efficiency:
    tier-1:
      cost: "rubber_high:10"
      level: 1
    tier-2:
      cost: "rubber_high:20"
      level: 2

  fast-respawn:
    cost: "rubber_high:10"
    delay: 10

  trap:
    cost: "rubber_high:10"
    range: 15