game:
  display-name: "§eКарта 1"
  description: "Спартакиада"

  time-of-day: 6000
  weather: clear

  resource-spawners:
    # Смола
    rubber_low:
      - "6, 72, 109, 0, 0" # ОРАНЖЕВЫЕ
      - "-109, 72, 6, 0, 0" # СИНИЕ
      - "-6, 72, -109, 0, 0" # РОЗОВЫЕ
      - "109, 72, -6, 0, 0" # ЗЕЛЕНЫЕ

    # Кирпичи
    rubber_mid:
      - "6, 73, 109, 0, 0" # ОРАНЖЕВЫЕ
      - "-109, 73, 6, 0, 0" # СИНИЕ
      - "-6, 73, -109, 0, 0" # РОЗОВЫЕ
      - "109, 73, -6, 0, 0" # ЗЕЛЕНЫЕ

    # Блоки
    rubber_high:
      - "-64, 71, 70, 0, 0" # ОРАНЖЕВЫЕ СИНИЕ 1
      - "-78, 71, 73, 0, 0" # ОРАНЖЕВЫЕ СИНИЕ 2
      - "-70, 71, -64, 0, 0" # СИНИЕ РОЗОВЫЕ 1
      - "-73, 71, -78, 0, 0" # СИНИЕ РОЗОВЫЕ 2
      - "64, 71, -70, 0, 0" # РОЗОВЫЕ ЗЕЛЕНЫЕ 1
      - "78, 71, -73, 0, 0" # РОЗОВЫЕ ЗЕЛЕНЫЕ 2
      - "70, 71, 64, 0, 0" # ЗЕЛЕНЫЕ ОРАНЖЕВЫЕ 1
      - "73, 71, 78, 0, 0" # ЗЕЛЕНЫЕ ОРАНЖЕВЫЕ 2

  # Торговцы +
  trader-locations:
    - "5.5, 71, 102.5, -90, 0" # ОРАНЖЕВЫЕ
    - "-101.5, 71, 5.5, 0, 0" # СИНИЕ
    - "-4.5, 71, -101.5, 90, 0" # РОЗОВЫЕ
    - "102.5, 71, -4.5, 180, 0" # ЗЕЛЕНЫЕ

  # Команды +
  team-spawns:
    - "8, 72, 97, 180, 0" # ОРАНЖЕВЫЕ
    - "-97, 72, 8, -90, 0" # СИНИЕ
    - "-8, 72, -97, 0, 0" # РОЗОВЫЕ
    - "97, 72, -8, 90, 0" # ЗЕЛЕНЫЕ

  # Ядра +
  core-locations:
    - "0, 71, 103, 0, 0" # ОРАНЖЕВЫЕ
    - "-103, 71, 0, 0, 0" # СИНИЕ
    - "0, 71, -103, 0, 0" # РОЗОВЫЕ
    - "103, 71, 0, 0, 0" # ЗЕЛЕНЫЕ

  # Прокачки +
  upgrade-locations:
    - "-6, 71, 100, 0, 0" # ОРАНЖЕВЫЕ
    - "-100, 71, -6, 0, 0" # СИНИЕ
    - "6, 71, -100, 0, 0" # РОЗОВЫЕ
    - "100, 71, 6, 0, 0" # ЗЕЛЕНЫЕ

  # Глазалии +
  eyeblossom-locations:
    - "25, 70, 1, 0, 0"
    - "23, 70, 5, 0, 0"
    - "20, 70, 6, 0, 0"
    - "21, 70, 8, 0, 0"
    - "17, 70, 10, 0, 0"
    - "16, 70, 19, 0, 0"
    - "12, 70, 16, 0, 0"
    - "10, 70, 18, 0, 0"
    - "13, 70, 20, 0, 0"
    - "11, 70, 21, 0, 0"
    - "7, 70, 18, 0, 0"
    - "4, 70, 23, 0, 0"
    - "2, 70, 22, 0, 0"
    - "2, 70, 27, 0, 0"
    - "-4, 70, 20, 0, 0"
    - "-5, 70, 22, 0, 0"
    - "-11, 70, 22, 0, 0"
    - "-14, 70, 21, 0, 0"
    - "-10, 70, 16, 0, 0"
    - "-14, 70, 15, 0, 0"
    - "-15, 70, 13, 0, 0"
    - "-20, 70, 13, 0, 0"
    - "-22, 70, 7, 0, 0"
    - "-21, 70, 2, 0, 0"
    - "-19, 70, 2, 0, 0"
    - "-20, 70, -4, 0, 0"
    - "-24, 70, -4, 0, 0"
    - "-21, 70, -6, 0, 0"
    - "-22, 70, -11, 0, 0"
    - "-16, 70, -14, 0, 0"
    - "-13, 70, -20, 0, 0"
    - "-12, 70, -18, 0, 0"
    - "-10, 70, -24, 0, 0"
    - "-6, 70, -26, 0, 0"
    - "-3, 70, -23, 0, 0"
    - "-1, 70, -22, 0, 0"
    - "-0, 70, -25, 0, 0"
    - "5, 70, -19, 0, 0"
    - "10, 70, -21, 0, 0"
    - "12, 70, -17, 0, 0"
    - "15, 70, -17, 0, 0"
    - "11, 70, -15, 0, 0"
    - "20, 70, -13, 0, 0"
    - "17, 70, -10, 0, 0"
    - "20, 70, -10, 0, 0"
    - "18, 70, -7, 0, 0"
    - "22, 70, -5, 0, 0"
    - "20, 70, -3, 0, 0"
    - "24, 70, -1, 0, 0"

  # Точка спавна Скрипуна
  creaking-spawns:
    - "25, 72, 0, 0, 0"
    - "-25, 72, 0, 0, 0"
    - "0, 72, 25, 0, 0"
    - "0, 72, -25, 0, 0"