name: ${NAME}
version: ${VERSION}
api-version: ${MINECRAFT_VERSION}
main: ru.joutak.creakywars.CreakyWars
description: 'creakywars'
authors: ['Kostyamops', 'EnderDissa']
website: ${WEBSITE}

depend: [Multiverse-Core]

commands:
  creakywars:
    description: "CreakyWars admin utilities"
    usage: "/creakywars reload"

permissions:
  creakywars.admin:
    description: "Admin tools for CreakyWars"
    default: op

libraries:
  - 'org.jetbrains.kotlin:kotlin-stdlib:${KOTLIN_VERSION}'
